--- 
nsxt_default_mtu: "1600"
nsxt_ssh_enabled: true
nsxt_status_check_delay: "50"
nsxt_validate_certs: false
state: present

nsx_node1: 
  hostname: iacnsxm01.dryicelabs.com
  nsxt_deployment_cluster: Compute-Cluster
  nsxt_deployment_datacenter: IAC-PDC
  nsxt_deployment_datastore: shared_storage_01
  nsxt_deployment_portgroup: vlan1002
  nsxt_network_ip_address: "10.1.22.3"

uplink_profiles: 
  - description: "This Profile is used for ESXi Host NVDS uplink connectivity"
    display_name: UP-ESXi_Host-Active_Active
    mtu: "9000"
    teaming:
      active_list:
        - uplink_name: "Uplink_VMNIC1"
        - uplink_name: "Uplink_VMNIC2"
          uplink_type: PNIC
      policy: Load Balance Source     
    transport_vlan: "1003"

  - description: "This Profile is used for Edge VM Embedded NVDS uplink connectivity"
    display_name: UP-Edge_VM-Active_Active
    mtu: "9000"
    teaming:
      active_list:
        - uplink_name: "Uplink_VMNIC1"
        - uplink_name: "Uplink_VMNIC2"
          uplink_type: PNIC
      policy: Load Balance Source
    transport_vlan: "1004"
