---
# tasks file for roles/nsxt_create_transport_zones
- name: Create transport zone
  nsxt_transport_zones:
    hostname: "{{ nsx_node1.nsxt_network_ip_address }}"
    username: "{{ nsxt_username }}"
    password: "{{ nsxt_password }}"
    validate_certs: "{{ nsxt_validate_certs }}"
    resource_type: "TransportZone"
    display_name: "{{ item.display_name }}"
    description: "{{ item.description }}"
    transport_type: "{{ item.transport_type }}"
    host_switch_name: "{{ item.host_switch_name }}"
    state: "{{ state }}"
  with_items:
    - "{{ transport_zones }}"
    

