---
# vars file for roles/nsxt_add_compute_manager
{
# One or more compute managers that have to be registered with NSX
  #
  "compute_managers": [
    {
      "display_name": "vcenter-iac",
      "mgmt_ip": "10.1.22.2",
      "origin_type": "vCenter",
      "credential_type": "UsernamePasswordLoginCredential",
      "username": '{{ lookup("env", "VMWARE_USER") }}',
      "password": '{{ lookup("env", "VMWARE_PASSWORD") }}',
    }
  ],

# NSX-T OVF/OVA Variables
  nsxt_ovftool_path: "/usr/bin",
  nsxt_ova_path: "/mnt/iso/VMware/NSX/NSX-T/v-3.x",
  nsxt_ova_filename: "nsx-unified-appliance-3.0.2.0.0.16887203.ova",
  
  ## NTP Servers
  ntp_server_default: 10.1.22.10,
  ntp_server_1: "",
  ntp_server_2: "",
  ntp_server_3: "",
  ntp_server_4: "",

  # DNS Servers
  dns_server_1: 10.1.22.10,
  dns_server_2: "blank",
  
  # DNS Default Domain
  dns_default_domain: 10.1.22.10,
  
  #NSX-T Gateway
  nsxt_network_gateway: "10.1.10.254",
  nsxt_network_netmask: "255.255.255.0",

  # NSX-T Default Deployment Variables
  nsxt_deployment_size: "small",
  nsxt_role: "NSX Manager",
  nsxt_origin_type: "vCenter",
  
  # SDDC NSX-T User Accounts
  nsxt_admin_username: "admin",
  nsxt_admin_password: "Admin@1Admin@1",
  nsxt_cli_password: "Admin@1Admin@1",

  ## Compute Manager User Permissions.
  # This account is used to connect NSX-T to the compute manager
  nsxt_cm_username: svc_iac_nsxt@dryicelab.com,
  nsxt_cm_password: password1,


  # NSX-T Misc Variables
  nsxt_ssh_enabled: True,
  nsxt_validate_certs: False,
  nsxt_status_check_delay: 50,
  nsxt_default_mtu: 1600,


  #First NSX appliance node. Defined separate based on the consumption.
    # Accepts both IP (IPv4) and FQDN for 'mgmt_ip'
    #
    "nsx_node1": {
      "hostname": "iacnsxm01.dryicelabs.com",
      "nsxt_network_ip_address": "10.1.22.3",
      "nsxt_deployment_datacenter": "IAC-PDC",
      "nsxt_deployment_cluster": "Compute-Cluster",
      "nsxt_deployment_datastore": "shared_storage_01",
      "nsxt_deployment_portgroup": "vlan1002"
  },

  #
  # Additional nodes defined as an array so that its easier to iterate
  # through them in the playbook.
  #
  "additional_nodes": [
    {
      "hostname": "iacnsxm02.dryicelabs.com",
      "nsxt_network_ip_address": "10.1.22.4",
      "prefix": "24",
      "nsxt_deployment_datacenter": "IAC-PDC",
      "nsxt_deployment_cluster": "Compute-Cluster",
      "nsxt_deployment_datastore": "shared_storage_01",
      "nsxt_deployment_portgroup": "vlan1002"
    },
    {
      "hostname": "iacnsxm03.dryicelabs.com",
      "nsxt_network_ip_address": "10.1.22.5",
      "prefix": "24",
      "nsxt_deployment_datacenter": "IAC-PDC",
      "nsxt_deployment_cluster": "Compute-Cluster",
      "nsxt_deployment_datastore": "shared_storage_01",
      "nsxt_deployment_portgroup": "vlan1002"
      }
  ],
}
