---
# tasks file for roles/nsxt_add_compute_managers
- name: "Add Compute Manager: {{ item.display_name }}"
  nsxt_fabric_compute_managers:
    hostname: "{{ nsx_node1.hostname }}"
    username: "{{ nsxt_admin_username }}"
    password: "{{ nsxt_admin_password }}"
    validate_certs: "{{ nsxt_validate_certs }}"
    display_name: "{{ item.display_name }}"
    server: "{{ item.mgmt_ip }}"
    origin_type: "{{ item.origin_type }}"
    credential:
      credential_type: "{{ item.credential_type }}"
      username: "{{ item.username }}"
      password: "{{ item.password }}"
    state: present
  with_items:
    - "{{compute_managers}}"
