nsxt_ovftool_path: /usr/bin
nsxt_ova_path: /mnt/iso/VMware/NSX/NSX-T/v-3.x
nsxt_ova_filename: nsx-unified-appliance-3.0.2.0.0.16887203.ova
ntp_server_default: 10.1.22.10
ntp_server_1: ''
ntp_server_2: ''
ntp_server_3: ''
ntp_server_4: ''
dns_server_1: 10.1.22.10
dns_server_2: blank
dns_default_domain: 10.1.22.10
nsxt_network_gateway: 10.1.10.254
nsxt_network_netmask: 255.255.255.0
nsxt_deployment_size: small
nsxt_role: NSX Manager
nsxt_origin_type: vCenter
nsxt_admin_username: admin
nsxt_admin_password: Admin@1Admin@1
nsxt_cli_password: Admin@1Admin@1
nsxt_cm_username: svc_iac_nsxt@dryicelab.com
nsxt_cm_password: password1
nsxt_ssh_enabled: true
nsxt_validate_certs: false
nsxt_status_check_delay: 50
nsxt_default_mtu: 1600
nsx_node1:
  hostname: iacnsxm01.dryicelabs.com
  nsxt_network_ip_address: 10.1.22.3
  nsxt_deployment_datacenter: IAC-PDC
  nsxt_deployment_cluster: Compute-Cluster
  nsxt_deployment_datastore: shared_storage_01
  nsxt_deployment_portgroup: vlan1002
additional_nodes:
  - hostname: mynsx-02.mylab.local
    mgmt_ip: 10.114.200.42
    prefix: '27'
    datacenter: Datacenter
    cluster: Management
    datastore: datastore36
    portgroup: VM Network
  - hostname: mynsx-03.mylab.local
    mgmt_ip: 10.114.200.43
    prefix: '27'
    datacenter: Datacenter
    cluster: Management
    datastore: datastore36
    portgroup: VM Network
